package it.unicam.cs.pa.swarmsimulator.model;

/**
 * A Robot interface is used to represent a robot in the swarm. A robot collects and updates navigation data,
 * describing its movement and signaling data at a given time.
 * After executing a command, a robot updates its navigation data accordingly to the new data generated by
 * the command execution.
 *
 * @param <S> the type of navigation state of this robot.
 */
public interface Robot<S extends RobotState> {
    /**
     * Returns the identifier for this robot.
     *
     * @return the identifier for this robot.
     */
    long getId();

    /**
     * Returns the current navigation state of this robot.
     *
     * @return the current navigation state of this robot.
     */
    S getNavigationState();

    /**
     * Updates the current navigation state of this robot with the new navigation state.
     * @param s the new navigation state.
     */
    void updateNavigationState(S s);

}
